:imagesdir: adocImages
:doctype:   article
:encoding:  utf-8
:lang:      en
:toc:       left
:toclevels: 5
:toc-title: Table of Content
:revdate:   Jan 22, 2020
:copyright: QFPI, 2019
:revnumber: V0.1
:sectnums:
:last-update-label!:
:nofooter!:
:media:     print
:icons:  font
:pagenums:

= Effective Of Java
[discrete]
== Change Log

[cols="20,20,60"]
|====
|Date|Author|Change

| Jan 22, 2020 | Jonny
| Initial Documents
|====

== Navigate

Command+O -> search class

Shift+Command+O -> search file

Option+Command+O -> symbol lookup

double shitf -> search all

on command+O

you can navigate the code line by put example Product:40
it will go to line 40

Command+O -> new class on project folder

Control+Option+N -> new class on class editor

Command+> or < -> resize windows

Command+1 -> hide show project folder

Command+E -> Jump between two edited file

Command+Shift+E -> Recent edited file


Command+] -> Jump Cursor forward

Command+{ -> Jump Cursor backward

Shift+Command+Delete - > Last edited line

Shift+Command+N -> ScratchFile

turn off you tab , you no need tab

Command+E -> show recent opened file
SHITF+Command+E -> show recent edited file

Command+, -> Preference

Command+N -> Generate constructor or getter setter

To Move Code

first select line by putting at the begining of line
Command+<  and then Shift+option+UpArrow or DownArrow

== Control
Control+I -> implements method

Control+O -> Override method

Control+G -> hightlight selected text and can change it impacting all seleced text

Control+Command+G -> select all higlighted text and can change in 1 shot


Option+Command+L - > Format Code Identation entire class

Inject Language, example you to write json string
OPTION+Eenter -> inject language then enter and type JSON
Then type OPTION+Enter again select JSON

or you can select Regex and alt enter again to check regex value

SHIFT+CONTROL+SPACE -> smart completion
CONTROL+Space -> Completion

completion using variabe

ALT+/ -> eample you declare 3 string s1,s2,s3, when you type ALT+/ it will auto complete


Alt+Command+T - > Surround code

SHITF+COMMAND+ENTER -> auto ; statement code or you type if(person == null) then ShiftCommandEnter it auto create bracket

COMMAND+D -> duplicate line

HTML Code completion
#myDiv>ul>li*5 then tab -> this will generated 5 li inside div

Command+F12 -> showing all class method

Command+Up -> show navigation bar

Shift+F2 -> code inspections to check the error

Ccontrol+ALT+O -> remove unwanted import


Refactoring..

Option+Command+V -> extract variable

Option+Command+M -> refactor selected code to method

Option+Command+P -> refactor to parameter


Test..

Shift+Command+T -> create test classes
